#ifndef __SimulateClientMainFrame__
#define __SimulateClientMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "MainFrame.h"
#include "NetWorkListener.h"


//// end generated include

/** Implementing MainFrame */
class SimulateClientMainFrame : public MainFrame
{
	protected:
		// Handlers for MainFrame events.
		void onMainFrameKeyDown( wxKeyEvent& event );
		void onSelectServer( wxCommandEvent& event );
		void onSelectMessage( wxCommandEvent& event );
		void OnSend( wxCommandEvent& event );

		virtual void OnMessageTextKeyup( wxKeyEvent& event );


public:

		/**连接服务器*/
		void updateServerList(const AddressVector& serverLister);

		/**初始化所有的消息id*/
		void initMessageID();

		/**消息字符转id*/
		unsigned int stringToMessageID(const std::string& message);


		///加条发送的消息
		void addReceiveMessage(const std::string& message,RakNet::SystemAddress& Address);
		

		///加入一条接收的消息
		void addSendMessage(const wxString& message);



	public:
		/** Constructor */
		SimulateClientMainFrame( wxWindow* parent );
	//// end generated class members


		typedef std::map<std::string,unsigned int>MessageIDMap;
		MessageIDMap  m_MessageMap;
	
};

#endif // __SimulateClientMainFrame__
